### ISSUE TITLE
Ready homework

### ISSUE THREAD

**Issue by kramarmm** [Artinov/home-work-10-kramarmm#1]
I read on learn.javascript.ru about mocha and chain tests.
But there is only one test succesfully passed (maybe becouse this function was written by me).
For another func like CountActiveTodos() no used HTML elements on test document. So I need to imitate general app HTML?

Most of functions is anonymous, So I can't apply to it.

And also I'm not surely understand how we need to make refactoring of this code. Becouse it bound to each other.

**Comment by eko24ive** [comment]
Nice issue, already love it !
You may call your test files in app !
Test for `countActiveTodos()` fails because it's depends on `todosLeft` variable, which refers span element which isn't placed in your test.html file. So you may transfer your code for testing into todo app. Just a not *imitate* is probably not the word you need, use *simulate*/*emulate* insted

Then your assertion have typo `undefind` which must be `undefined`.
And secondly - it is wrong to compare this method to any value because it doesn't `return` anything !
Instead it is better to check if `todosLeft.innerHtml` was updated.

What issues are you having with anonymous functions ? I just can't understand.

Regarding refactoring - there is some part of code which could be optimized - we discussed it today.

**Comment by eko24ive** [comment]
@kramarmm  by the way, it would be better if you'd check `todosLeft.innerHtml` before calling `countActiveTodos()` and after.
